Samba

diff --git a/samba-ad-dc/script/samba b/samba-ad-dc/script/samba
--- a/samba-ad-dc/script/samba
+++ b/samba-ad-dc/script/samba
@@ -120,7 +120,7 @@ samba_status()
 samba_setup () {
 
         # Set variables
-        DOMAIN=${DOMAIN:-UZ.COM.BR}
+        DOMAIN=${DOMAIN:-UZ.INTRANET}
         DOMAINPASS=${DOMAINPASS:-Uz2@21TI}
         JOIN=${JOIN:-false}
         JOINSITE=${JOINSITE:-NONE}
@@ -133,10 +133,6 @@ samba_setup () {
         LDOMAIN=${DOMAIN,,}
         UDOMAIN=${DOMAIN^^}
         URDOMAIN=${UDOMAIN%%.*}
-
-        if [[ ! -f /var/lib/samba/smb.conf ]]; then
-                mount -t glusterfs -o acl localhost:volume-samba /var/lib/samba
-        fi
 
         # If multi-site, we need to connect to the VPN before joining the domain
         if [[ ${MULTISITE,,} == "true" ]]; then
@@ -218,6 +214,20 @@ samba_start()
                 COMMAND="$OCF_RESKEY_binpath"
         else
                 COMMAND="/usr/sbin/samba"
+        fi
+
+        HEALTHY_BRICKS=$(gluster volume heal volume-samba info summary| grep -A2 "Brick $HOSTNAME"|grep "Total Number of entries: 0"|wc -l)
+        if [ $HEALTHY_BRICKS != 1 ]; then
+                ocf_log err "Error. GlusterFS is unhealthy, try manual heal to fix."
+                exit $OCF_ERR_GENERIC
+        fi
+
+        if ! (grep -qs '/var/lib/samba ' /proc/mounts;) then
+                mount -t glusterfs -o acl localhost:volume-samba /var/lib/samba
+                if ! (grep -qs '/var/lib/samba ' /proc/mounts;) then
+                    ocf_log err "Error. Can't mount glusterfs partition."
+                    exit $OCF_ERR_GENERIC
+                fi
         fi
 
         samba_setup
