Zabbix

diff --git a/zabbix/scripts/mysqlSVC b/zabbix/scripts/mysqlSVC
--- a/zabbix/scripts/mysqlSVC
+++ b/zabbix/scripts/mysqlSVC
@@ -152,6 +152,12 @@ mysql_start()
                 COMMAND="service mysql start"
         fi
 
+        HEALTHY_BRICKS=$(gluster volume heal volume-zabbix info summary| grep "Total Number of entries: 0"|wc -l)
+        if [ $HEALTHY_BRICKS != 2 ]; then
+                ocf_log err "Error. GlusterFS is unhealthy, try manual heal to fix."
+                exit $OCF_ERR_GENERIC
+        fi
+
 	if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
                 mount -t glusterfs -o acl localhost:volume-zabbix /var/lib/mysql
 		if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
