Zabbix

diff --git a/postgresql/scripts/postgreSVC b/postgresql/scripts/postgreSVC
--- a/postgresql/scripts/postgreSVC
+++ b/postgresql/scripts/postgreSVC
@@ -117,6 +117,23 @@ postgresql_status()
         return $OCF_NOT_RUNNING
 }
 
+is_isolation()
+{
+        cnt=3
+        testIP=<check_isolation_ip>
+        #testIP=1.2.3.4
+        nodePeer=<nodePeer>
+        #nodePeer=1.2.3.4
+        recv=$(/bin/ping -c 1 -w 3 -q $nodePeer | grep received | cut -d, -f2 | awk '{print $1}')
+        if [ "$recv" -eq 0 ]; then
+            recv=$(/bin/ping -c $cnt -q $testIP | grep received | cut -d, -f2 | awk '{print $1}')
+            if [ "$recv" -eq 0 ]; then
+                return 1
+            fi
+        fi
+        return 0
+}
+
 postgresql_start()
 {
         # if postgresql_ is running return success
@@ -129,11 +146,11 @@ postgresql_start()
                 exit $OCF_ERR_GENERIC
         fi
 
-        #if [ -n "$OCF_RESKEY_binpath" ]; then
-        #        COMMAND="$OCF_RESKEY_binpath"
-        #else
-                #COMMAND="su postgres -c \"/usr/lib/postgresql/11/bin/pg_ctl start -D /etc/postgresql/11/main/\""
-        #fi
+	is_isolation
+        if [ $? -eq 1 ]; then
+            ocf_log err "Error. Node is alone, process halted to avoid active-active."
+            exit $OCF_ERR_GENERIC
+        fi
 
 	drbdadm primary drbd --force
         retVal=$?
diff --git a/zabbix/scripts/mysqlSVC b/zabbix/scripts/mysqlSVC
--- a/zabbix/scripts/mysqlSVC
+++ b/zabbix/scripts/mysqlSVC
@@ -152,25 +152,26 @@ mysql_start()
                 COMMAND="service mysql start"
         fi
 
-        if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
-                mount -t glusterfs -o acl localhost:volume-zabbix /var/lib/mysql
-                if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
-                    ocf_log err "Error. Can't mount glusterfs partition."
-                    exit $OCF_ERR_GENERIC
-                fi
-        fi
-
-        HEALTHY_BRICKS=$(gluster volume heal volume-zabbix info summary | grep -A4 "Brick $HOSTNAME"|grep "Number of entries in split-brain: 0"|wc -l)
-        if [ $HEALTHY_BRICKS != 1 ]; then
-                ocf_log err "Error. GlusterFS is unhealthy, try manual heal to fix."
-                exit $OCF_ERR_GENERIC
-        fi
-
 	is_isolation
 	if [ $? -eq 1 ]; then
             ocf_log err "Error. Node is alone, process halted to avoid active-active."
             exit $OCF_ERR_GENERIC
 	fi
+
+	drbdadm primary drbd --force
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+                ocf_log err "Error. Can't bring DRBD node as primary."
+                exit $OCF_ERR_GENERIC
+        fi
+
+	if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
+                mount -o acl /dev/drbd0 /var/lib/mysql
+                if ! (grep -qs '/var/lib/mysql ' /proc/mounts;) then
+                    ocf_log err "Error. Can't mount MySQL DRBD partition."
+                    exit $OCF_ERR_GENERIC
+                fi
+        fi
 
         $COMMAND
         if [ $? -ne 0 ]; then
@@ -198,6 +199,9 @@ mysql_stop()
                                 fi
                         fi
                         rm $PIDFILE 2>/dev/null
+
+			umount -f /var/lib/mysql
+		        drbdadm secondary drbd
                 fi
         fi
         ocf_log info "Stopped mysql daemon."
