Samba

diff --git a/samba-ad-dc/scripts/postfilebackup b/samba-ad-dc/scripts/postfilebackup
--- a/samba-ad-dc/scripts/postfilebackup
+++ b/samba-ad-dc/scripts/postfilebackup
@@ -1,18 +1,11 @@
 #!/bin/bash
-echo "umount snapshot" >> /tmp/urbackup.log
-umount /mnt/samba
-echo "deactivate snapshot" >> /tmp/urbackup.log
-echo y|gluster snapshot deactivate snap-backup
-echo "delete snapshot" >> /tmp/urbackup.log
-echo y|gluster snapshot delete snap-backup
-
-echo "umount snapshot shares" >> /tmp/urbackup.log
-umount /mnt/shares
-echo "deactivate snapshot shares" >> /tmp/urbackup.log
-echo y|gluster snapshot deactivate snap-backup-shares
-echo "delete snapshot shares" >> /tmp/urbackup.log
-echo y|gluster snapshot delete snap-backup-shares
-
-echo "done" >> /tmp/urbackup.log
+echo "$(date) Remove snapshot" >> /tmp/drbd-snapshot.log
+btrfs subvolume delete /var/lib/samba/.snapshots/backup
+if [ -d "/var/lib/samba/.snapshots/backup" ]; then
+        echo "$(date) Fail removing snapshot" >> /tmp/drbd-snapshot.log
+        exit 1
+else
+        echo "$(date) Success removing snapshot" >> /tmp/drbd-snapshot.log
+fi
 exit 0
 
diff --git a/samba-ad-dc/scripts/prefilebackup b/samba-ad-dc/scripts/prefilebackup
--- a/samba-ad-dc/scripts/prefilebackup
+++ b/samba-ad-dc/scripts/prefilebackup
@@ -1,37 +1,17 @@
 #!/bin/bash
-echo "Create snapshot" > /tmp/urbackup.log
-gluster snapshot create snap-backup volume-samba no-timestamp
-echo "Activate snapshot" >> /tmp/urbackup.log
-gluster snapshot activate snap-backup
-echo "Mount snapshot" >> /tmp/urbackup.log
-mount -t glusterfs localhost:/snaps/snap-backup/volume-samba /mnt/samba
-if ! (grep -qs '/mnt/samba ' /proc/mounts;) then
-        echo "Snapshot fail"
+echo "$(date) Backup Samba database" > /tmp/drbd-snapshot.log
+rm -r -f /var/lib/samba/backup/*.bz2
+/usr/bin/samba-tool domain backup online --targetdir=/var/lib/samba/backup -UAdministrator --server=192.168.1.249 --password=<domain_password>
+[ $? -eq 0 ]  || exit 1
+rm -r -f /var/lib/samba/backup/tmp*
 
-        echo y|gluster snapshot deactivate snap-backup
-        echo y|gluster snapshot delete snap-backup
-
+echo "$(date) Create snapshot" >> /tmp/drbd-snapshot.log
+btrfs subvolume snapshot -r /var/lib/samba/ /var/lib/samba/.snapshots/backup
+if [ -d "/var/lib/samba/.snapshots/backup" ]; then
+        echo "$(date) Success snapshot" >> /tmp/drbd-snapshot.log
+else
+        echo "$(date) Fail snapshot" >> /tmp/drbd-snapshot.log
         exit 1
 fi
-
-echo "Create snapshot shares" >> /tmp/urbackup.log
-gluster snapshot create snap-backup-shares volume-shares no-timestamp
-echo "Activate snapshot shares" >> /tmp/urbackup.log
-gluster snapshot activate snap-backup-shares
-echo "Mount snapshot shares" >> /tmp/urbackup.log
-mount -t glusterfs localhost:/snaps/snap-backup-shares/volume-shares /mnt/shares
-if ! (grep -qs '/mnt/shares ' /proc/mounts;) then
-        echo "Snapshot shares fail"
-
-        echo y|gluster snapshot deactivate snap-backup
-        echo y|gluster snapshot delete snap-backup
-
-        echo y|gluster snapshot deactivate snap-backup-shares
-        echo y|gluster snapshot delete snap-backup-shares
-
-        exit 1
-fi
-
-echo "Success snapshot" >> /tmp/urbackup.log
-echo "Snapshot success"
 exit 0
+
